# And now introducing Pandas...

- Named after a cute animal?
- Open source (free) Python library.
- Most widely package for data analysis.
- Future-proof: used for AI and machine learning tasks.

## Import Pandas

Unlike the pure Python we've written so far, we have to import Pandas which brings ALL its functionality into our iPython Notebook (```.ipynb```).

In [3]:
## import pandas
import pandas as pd

## Import CVS data into our Jupyter notebook

**Stay organizing!**

### Read a CSV file into your notebook

#### Bring in ```insurance.csv``` into Pandas

- You must provide a ```path``` to the file you are importing.

Syntax: ```pd.read_csv("path_to_file")```

### Read and hold CSV content into a ```dataframe```

The naming convention is to call it a ```df```

In [4]:
## simply read the csv file when data file is at the same level
# Esto se llama panda data frame
# Poner los datos en la misma carpeta, para poder llamarlos fácil
df = pd.read_csv("data/insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

## Explore our dataframe

In [10]:
## call the df
## returns the first 5 and last 5 rows
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [11]:
## call the top only
## returns first 5
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [12]:
## call the top n rows
n = 10
df.head(n)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [13]:
## call the last 5 
df.tail(5)

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603

In [14]:
## call the last n
df.tail(n)

      age     sex     bmi  children smoker     region      charges
1328   23  female  24.225         2     no  northeast  22395.74424
1329   52    male  38.600         2     no  southwest  10325.20600
1330   57  female  25.740         2     no  southeast  12629.16560
1331   23  female  33.400         0     no  southwest  10795.93733
1332   52  female  44.700         3     no  southwest  11411.68500
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

In [15]:
## call a random sample n number of rows
df.sample(n)

     age     sex     bmi  children smoker     region      charges
498   44  female  23.980         2     no  southeast   8211.10020
686   42    male  26.125         2     no  northeast   7729.64575
180   58    male  28.595         0     no  northwest  11735.87905
338   50    male  32.300         1    yes  northeast  41919.09700
730   35    male  24.420         3    yes  southeast  19361.99880
732   24  female  30.100         3     no  southwest   4234.92700
679   49  female  23.180         2     no  northwest  10156.78320
37    26    male  20.800         0     no  southwest   2302.30000
512   51    male  22.420         0     no  northeast   9361.32680
4     32    male  28.880         0     no  northwest   3866.85520

In [17]:
#type of element
type(df)

pandas.core.frame.DataFrame

In [18]:
## get basic overview of the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

## Importing a simple Excel file

Bring in ```global_life.xlsx``` into Pandas

In [19]:
## step 1. confirm that read returns a df
## step 2. place it into a df, call the df
pd.read_excel("data/sba-disaster-loans-18.xlsx")

               Instructions for Use of this Dataset
0  This dataset contains non-personally identifia...

In [35]:
## call the top 15 values
# Puedo usar un valor para abrir una hoja en particular
# Puedo saltear las columnas, en este caso las primeras 3
pd.read_excel("data/sba-disaster-loans-18.xlsx", sheet_name = 4, skiprows=4)

,SBA Physical Declaration Number,SBA EIDL Declaration Number,FEMA Disaster Number,SBA Disaster Number,Damaged Property City Name,Damaged Property Zip Code,Damaged Property County/Parish Name,Damaged Property State Code,Total Verified Loss,Verified Loss Real Estate,Verified Loss Content,Total Approved Loan Amount,Approved Amount Real Estate,Approved Amount Content,Approved Amount EIDL
0,NaN,15337.0,NaN,ZZ-00013,LOUISVILLE,40299.0,JEFFERSON,KY,0.0,0.0,0.0,49400.0,0.0,0.0,49400.0
1,NaN,15337.0,NaN,ZZ-00013,NORWOOD YOUNG AMERICA,55368.0,CARVER,MN,0.0,0.0,0.0,49700.0,0.0,0.0,49700.0
2,NaN,15359.0,NaN,FL-00133,ALTAMONTE SPRINGS,32714.0,SEMINOLE,FL,0.0,0.0,0.0,7000.0,0.0,0.0,7000.0
3,NaN,15359.0,NaN,FL-00133,APOPKA,32712.0,ORANGE,FL,0.0,0.0,0.0,25000.0,0.0,0.0,25000.0
4,NaN,15359.0,NaN,FL-00133,AVENTURA,33180.0,MIAMI-DADE,FL,0.0,0.0,0.0,162300.0,0.0,0.0,162300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,15622,15623.0,4382.0,CA-00288,SHASTA,96087.0,Shasta,CA,227915.0,198265.0,29650.0,195100.0,161400.0,29700.0,4000.0
822,15626,15627.0,NaN,NE-00071,PENDER,68047.0,Thurston,NE,7592.0,7592.0,0.0,7600.0,7600.0,0.0,NaN
823,15642,15643.0,NaN,NM-00062,SANTA FE,87505.0,Santa Fe,NM,24472.0,22872.0,1600.0,24500.0,22900.0,1600.0,NaN
824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,United States Small Business Administration (S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
#Puedo llamar la hoja con el nombre
df = pd.read_excel("data/sba-disaster-loans-18.xlsx", 
              sheet_name = "FY18 Business", skiprows=4)
df

,SBA Physical Declaration Number,SBA EIDL Declaration Number,FEMA Disaster Number,SBA Disaster Number,Damaged Property City Name,Damaged Property Zip Code,Damaged Property County/Parish Name,Damaged Property State Code,Total Verified Loss,Verified Loss Real Estate,Verified Loss Content,Total Approved Loan Amount,Approved Amount Real Estate,Approved Amount Content,Approved Amount EIDL
0,NaN,15337.0,NaN,ZZ-00013,LOUISVILLE,40299.0,JEFFERSON,KY,0.0,0.0,0.0,49400.0,0.0,0.0,49400.0
1,NaN,15337.0,NaN,ZZ-00013,NORWOOD YOUNG AMERICA,55368.0,CARVER,MN,0.0,0.0,0.0,49700.0,0.0,0.0,49700.0
2,NaN,15359.0,NaN,FL-00133,ALTAMONTE SPRINGS,32714.0,SEMINOLE,FL,0.0,0.0,0.0,7000.0,0.0,0.0,7000.0
3,NaN,15359.0,NaN,FL-00133,APOPKA,32712.0,ORANGE,FL,0.0,0.0,0.0,25000.0,0.0,0.0,25000.0
4,NaN,15359.0,NaN,FL-00133,AVENTURA,33180.0,MIAMI-DADE,FL,0.0,0.0,0.0,162300.0,0.0,0.0,162300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,15622,15623.0,4382.0,CA-00288,SHASTA,96087.0,Shasta,CA,227915.0,198265.0,29650.0,195100.0,161400.0,29700.0,4000.0
822,15626,15627.0,NaN,NE-00071,PENDER,68047.0,Thurston,NE,7592.0,7592.0,0.0,7600.0,7600.0,0.0,NaN
823,15642,15643.0,NaN,NM-00062,SANTA FE,87505.0,Santa Fe,NM,24472.0,22872.0,1600.0,24500.0,22900.0,1600.0,NaN
824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,United States Small Business Administration (S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
## call the last 3 values
df.tail(3)

,SBA Physical Declaration Number,SBA EIDL Declaration Number,FEMA Disaster Number,SBA Disaster Number,Damaged Property City Name,Damaged Property Zip Code,Damaged Property County/Parish Name,Damaged Property State Code,Total Verified Loss,Verified Loss Real Estate,Verified Loss Content,Total Approved Loan Amount,Approved Amount Real Estate,Approved Amount Content,Approved Amount EIDL
823,15642,15643.0,NaN,NM-00062,SANTA FE,87505.0,Santa Fe,NM,24472.0,22872.0,1600.0,24500.0,22900.0,1600.0,NaN
824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
825,United States Small Business Administration (S...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
## show 13 random rows 
df.sample(13)

,SBA Physical Declaration Number,SBA EIDL Declaration Number,FEMA Disaster Number,SBA Disaster Number,Damaged Property City Name,Damaged Property Zip Code,Damaged Property County/Parish Name,Damaged Property State Code,Total Verified Loss,Verified Loss Real Estate,Verified Loss Content,Total Approved Loan Amount,Approved Amount Real Estate,Approved Amount Content,Approved Amount EIDL
606,15696,15697.0,4393.0,NC-00099,NAKINA,28455.0,COLUMBUS,NC,12025.0,0.0,12025.0,0.0,0.0,0.0,0.0
484,15696,15697.0,4393.0,NC-00099,DELCO,28436.0,COLUMBUS,NC,9089.0,9089.0,0.0,0.0,0.0,0.0,0.0
127,NaN,15359.0,NaN,FL-00133,SARASOTA,34236.0,SARASOTA,FL,0.0,0.0,0.0,60000.0,0.0,0.0,60000.0
452,15696,15697.0,4393.0,NC-00099,CAPE CARTERET,28584.0,CARTERET,NC,124785.0,118785.0,6000.0,21800.0,21800.0,0.0,0.0
529,15696,15697.0,4393.0,NC-00099,GREENVILLE,27858.0,PITT,NC,17850.0,0.0,17850.0,225000.0,0.0,0.0,225000.0
170,NaN,15363.0,NaN,VI-00014,ST THOMAS,802.0,SAINT THOMAS,VI,0.0,0.0,0.0,59400.0,0.0,0.0,59400.0
666,15696,15697.0,4393.0,NC-00099,SHALLOTTE,28470.0,BRUNSWICK,NC,136427.0,23601.0,112826.0,229600.0,3200.0,30900.0,195500.0
791,15698,15699.0,4394.0,SC-00054,SOUTHPORT,28461.0,BRUNSWICK,NC,0.0,0.0,0.0,39900.0,0.0,0.0,39900.0
203,15342,15343.0,4340.0,VI-00012,Kingshill,850.0,SAINT CROIX,VI,169600.0,164079.0,5521.0,169600.0,164100.0,5500.0,0.0
191,NaN,15546.0,NaN,CO-00094,AUSTIN,81410.0,DELTA,CO,0.0,0.0,0.0,25000.0,0.0,0.0,25000.0
117,NaN,15359.0,NaN,FL-00133,REDINGTON SHORES,33708.0,PINELLAS,FL,0.0,0.0,0.0,25000.0,0.0,0.0,25000.0
335,15483,15484.0,NaN,AL-00086,HUNTSVILLE,35805.0,MADISON,AL,14812.0,14812.0,0.0,14900.0,14900.0,0.0,0.0
512,15696,15697.0,4393.0,NC-00099,FAYETTEVILLE,28312.0,CUMBERLAND,NC,189849.0,167419.0,22430.0,23100.0,23100.0,0.0,0.0

### What types of data or ```datatypes``` does this ```df``` hold?

In [25]:
## datatypes here
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 826 entries, 0 to 825
Data columns (total 15 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   SBA Physical Declaration Number      632 non-null    object
 1   SBA EIDL Declaration Number          824 non-null    float64
 2   FEMA Disaster Number                 575 non-null    float64
 3   SBA Disaster Number                  824 non-null    object
 4   Damaged Property City Name           824 non-null    object
 5   Damaged Property Zip Code            824 non-null    float64
 6   Damaged Property County/Parish Name  824 non-null    object
 7   Damaged Property State Code          824 non-null    object
 8   Total Verified Loss                  824 non-null    float64
 9   Verified Loss Real Estate            824 non-null    float64
 10  Verified Loss Content                824 non-null    float64
 11  Total Approved Loan Amount           824 non-null    float64
 12  Approved Amount Real Estate          823 non-null    float64
 13  Approved Amount Content              823 non-null    float64
 14  Approved Amount EIDL                 821 non-null    float64
dtypes: float64(10), object(5)
memory usage: 96.9+ KB

## Read two or more separate files and combine them.

Often, we have to work with ```bike_data_2019.csv```, ```bike_data_2020.csv```, etc.

But if we really want to see change over time, we need to combine these spreadsheets into a single spreadsheet.

Bring in ```flt_delays_17.csv``` and ```flt_delays_18.csv``` and combine them into a dataframe called ```delay_df```

In [32]:
df_2017 = pd.read_csv("data/flt-delays-17.csv")
df_2017.head(2)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2017,3,AA,American Airlines Inc.,ABQ,"Albuquerque, NM: Albuquerque International Sun...",145.0,26.0,10.83,0.00,...,0.0,9.31,0.0,0.0,935.0,437.0,0.0,193.0,0.0,305.0
1,2017,3,AA,American Airlines Inc.,ALB,"Albany, NY: Albany International",89.0,16.0,2.12,0.41,...,0.0,7.26,3.0,0.0,689.0,100.0,40.0,139.0,0.0,410.0

In [33]:
df_2018 = pd.read_csv("data/flt-delays-18.csv")
df_2018.head(2)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2018,1,MQ,Envoy Air,BIS,"Bismarck/Mandan, ND: Bismarck Municipal",5.0,3.0,1.00,0.06,...,0.0,0.00,0.0,0.0,104.0,54.0,1.0,49.0,0.0,0.0
1,2018,1,MQ,Envoy Air,BNA,"Nashville, TN: Nashville International",110.0,21.0,7.17,1.16,...,0.0,5.92,3.0,0.0,897.0,344.0,37.0,226.0,0.0,290.0

In [37]:
## confirm they are in similar columns
df_2017.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8384 entries, 0 to 8383
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 8384 non-null   int64
 1    month               8384 non-null   int64
 2   carrier              8384 non-null   object
 3   carrier_name         8384 non-null   object
 4   airport              8384 non-null   object
 5   airport_name         8384 non-null   object
 6   arr_flights          8377 non-null   float64
 7   arr_del15            8372 non-null   float64
 8   carrier_ct           8377 non-null   float64
 9    weather_ct          8377 non-null   float64
 10  nas_ct               8377 non-null   float64
 11  security_ct          8377 non-null   float64
 12  late_aircraft_ct     8377 non-null   float64
 13  arr_cancelled        8377 non-null   float64
 14  arr_diverted         8377 non-null   float64
 15   arr_delay           8377 non-null   float64
 16   carrier_delay       8377 non-null   float64
 17  weather_delay        8377 non-null   float64
 18  nas_delay            8377 non-null   float64
 19  security_delay       8377 non-null   float64
 20  late_aircraft_delay  8377 non-null   float64
dtypes: float64(15), int64(2), object(4)
memory usage: 1.3+ MB

In [38]:
## confirm they are in similar columns
df_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16791 entries, 0 to 16790
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 16791 non-null  int64
 1    month               16791 non-null  int64
 2   carrier              16791 non-null  object
 3   carrier_name         16791 non-null  object
 4   airport              16791 non-null  object
 5   airport_name         16791 non-null  object
 6   arr_flights          16775 non-null  float64
 7   arr_del15            16772 non-null  float64
 8   carrier_ct           16775 non-null  float64
 9    weather_ct          16775 non-null  float64
 10  nas_ct               16775 non-null  float64
 11  security_ct          16775 non-null  float64
 12  late_aircraft_ct     16775 non-null  float64
 13  arr_cancelled        16775 non-null  float64
 14  arr_diverted         16775 non-null  float64
 15   arr_delay           16775 non-null  float64
 16   carrier_delay       16775 non-null  float64
 17  weather_delay        16775 non-null  float64
 18  nas_delay            16775 non-null  float64
 19  security_delay       16775 non-null  float64
 20  late_aircraft_delay  16775 non-null  float64
dtypes: float64(15), int64(2), object(4)
memory usage: 2.7+ MB

In [40]:
## If we only want to see how many rows and columns
df_2017.shape

(8384, 21)

In [41]:
df_2018.shape

(16791, 21)

In [42]:
## confirm they are in similar columns
df_2018.shape[0]+df_2017.shape[0]

25175

In [43]:
## concat the two by placing both dataframes in a list
df_delays = pd.concat([df_2017,df_2018])
df_delays.shape

(25175, 21)

In [45]:
## How many total rows?
df_delays.shape[0]

25175

In [46]:
## what type of data is a shape
type(df_delays.shape)

tuple

In [48]:
## we can pull out values from a tuple, just like a list or dictionary

In [50]:
## the number of rows should add up correctly
## Dos == no son como hacer una asignacion de valor si no que pregunta si es igual, valida
df_2018.shape[0] + df_2017.shape[0] == df_delays.shape[0]

True

In [51]:
### Get a sample of the new df
df_delays.sample (10)

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
15921,2018,10,MQ,Envoy Air,AZO,"Kalamazoo, MI: Kalamazoo/Battle Creek Internat...",88.0,12.0,3.14,0.00,...,0.0,5.11,2.0,0.0,697.0,162.0,0.0,148.0,0.0,387.0
11955,2018,8,OO,SkyWest Airlines Inc.,JAX,"Jacksonville, FL: Jacksonville International",70.0,26.0,8.91,1.77,...,0.0,6.18,2.0,0.0,1814.0,807.0,106.0,347.0,0.0,554.0
14413,2018,9,AA,American Airlines Inc.,MLB,"Melbourne, FL: Melbourne International",30.0,4.0,1.86,1.00,...,0.0,0.24,0.0,0.0,233.0,147.0,23.0,48.0,0.0,15.0
591,2018,1,WN,Southwest Airlines Co.,AUS,"Austin, TX: Austin - Bergstrom International",1849.0,249.0,83.41,0.80,...,0.0,123.11,37.0,2.0,10668.0,3708.0,82.0,1156.0,0.0,5722.0
636,2018,1,WN,Southwest Airlines Co.,MEM,"Memphis, TN: Memphis International",267.0,43.0,19.68,0.60,...,0.0,18.38,7.0,0.0,2045.0,894.0,32.0,160.0,0.0,959.0
5737,2017,8,EV,ExpressJet Airlines Inc.,RST,"Rochester, MN: Rochester International",179.0,34.0,12.86,0.00,...,0.0,17.20,2.0,0.0,2190.0,709.0,0.0,84.0,0.0,1397.0
2854,2018,2,DL,Delta Air Lines Inc.,DAB,"Daytona Beach, FL: Daytona Beach International",121.0,13.0,4.87,2.19,...,0.0,4.53,0.0,0.0,1068.0,152.0,614.0,62.0,0.0,240.0
12150,2018,8,UA,United Air Lines Inc.,PBI,"West Palm Beach/Palm Beach, FL: Palm Beach Int...",143.0,55.0,11.79,5.29,...,0.0,20.65,7.0,0.0,4754.0,1206.0,764.0,921.0,0.0,1863.0
4475,2018,3,OO,SkyWest Airlines Inc.,LAS,"Las Vegas, NV: McCarran International",260.0,51.0,6.59,1.77,...,0.0,33.70,0.0,0.0,4259.0,529.0,77.0,370.0,0.0,3283.0
136,2017,3,AS,Alaska Airlines Inc.,PHX,"Phoenix, AZ: Phoenix Sky Harbor International",279.0,56.0,16.24,0.00,...,0.0,16.09,1.0,0.0,2210.0,617.0,0.0,604.0,0.0,989.0

## Pandas ```Series``` v. ```DataFrames```

#### A ```dataframe``` is two-dimensional labeled data structure...

![Screen Shot 2023-02-09 at 8.13.56 AM.png]()

#### A ```Series``` is a one-dimensional array of data.

#### Multiple ```series``` make up a ```dataframe```

The key is to know what you are working with because once again, there are specific operations you can run on a ```series``` that you can't run on a ```dataframe```, and vise versa.

# Retrieving data

We can store data in variables, lists and dictionaries. We'll also want to pull data from these objects.

## retrieving data from lists...

### 1. List basics:

In [53]:
## Run this cell to pull this list into memory:

toxic_chemicals = [
    "Polyvinyl Chloride",
    "PVC",
    "Perfluorooctanoic Acid",
    "PFOA",
    "Triclosan",
    "Bisphenol-A",
    "BPA",
    "Formaldehyde",
    "Naphthalene",
    "Asbestos"
]

In [54]:
## call the list
toxic_chemicals

['Polyvinyl Chloride',
 'PVC',
 'Perfluorooctanoic Acid',
 'PFOA',
 'Triclosan',
 'Bisphenol-A',
 'BPA',
 'Formaldehyde',
 'Naphthalene',
 'Asbestos']

In [55]:
## print the list
print (toxic_chemicals)

['Polyvinyl Chloride', 'PVC', 'Perfluorooctanoic Acid', 'PFOA', 'Triclosan', 'Bisphenol-A', 'BPA', 'Formaldehyde', 'Naphthalene', 'Asbestos']

In [56]:
## how long is this list?
len(toxic_chemicals)

10

In [58]:
#Desde el comienzo hasta el numero 4 (inclusive, o el 5 excluido)
toxic_chemicals[:5]

['Polyvinyl Chloride', 'PVC', 'Perfluorooctanoic Acid', 'PFOA', 'Triclosan']

In [59]:
#Desde el cuatro hasta el final
toxic_chemicals[4:]

['Triclosan', 'Bisphenol-A', 'BPA', 'Formaldehyde', 'Naphthalene', 'Asbestos']

### 2. Slicing to target items in a list

In [60]:
## Last time we used index() method to retrieve 
## the index position of an item:
toxic_chemicals.index("BPA")

6

#### Recall that the first value in almost every programming language is zero-indexed, or the count always starts at zero.

#### Either way, what we really want is to retrieve the data, not the index position

#### Now we want to retrieve the data, not the index

```list_name[index_position]```

In [62]:
toxic_chemicals [6] #fifth value

'BPA'

In [63]:
## call the penultimate item in the list
toxic_chemicals[-2]

'Naphthalene'

#### How about retrieving a subset of data and not just individual data points?

#### Slice notation

![Screen Shot 2022-02-24 at 4.57.54 PM.png]()

In [64]:
## Call the first 3 items:
toxic_chemicals[0:3]

['Polyvinyl Chloride', 'PVC', 'Perfluorooctanoic Acid']

#### This works on all lists – regardless of the data they hold.

In [65]:
#### Run this list of dictionaries

country_stats = [
  {'GDP': '$20.4 trillion',
  'NATO': True,
  'capital': 'Washington, DC',
  'country': 'United States',
  'currency': 'Dollar',
  'population': 329450000},
 {'GDP': '$1.4 trillion',
  'NATO': False,
  'capital': 'Moscow',
  'country': 'Russia',
  'currency': 'Ruble',
  'population': 145870000},
 {'GDP': '$155 Billion',
  'NATO': False,
  'capital': 'Kiev',
  'country': 'Ukraine',
  'currency': 'Hrywnja',
  'population': 44135000}
]

In [66]:
## call it
country_stats

[{'GDP': '$20.4 trillion',
  'NATO': True,
  'capital': 'Washington, DC',
  'country': 'United States',
  'currency': 'Dollar',
  'population': 329450000},
 {'GDP': '$1.4 trillion',
  'NATO': False,
  'capital': 'Moscow',
  'country': 'Russia',
  'currency': 'Ruble',
  'population': 145870000},
 {'GDP': '$155 Billion',
  'NATO': False,
  'capital': 'Kiev',
  'country': 'Ukraine',
  'currency': 'Hrywnja',
  'population': 44135000}]

In [67]:
### call the first item only
country_stats[0]

{'GDP': '$20.4 trillion',
 'NATO': True,
 'capital': 'Washington, DC',
 'country': 'United States',
 'currency': 'Dollar',
 'population': 329450000}

In [68]:
## what type of data is it?
type(country_stats[0])

dict

In [69]:
## call the first two items
country_stats[0:2]

[{'GDP': '$20.4 trillion',
  'NATO': True,
  'capital': 'Washington, DC',
  'country': 'United States',
  'currency': 'Dollar',
  'population': 329450000},
 {'GDP': '$1.4 trillion',
  'NATO': False,
  'capital': 'Moscow',
  'country': 'Russia',
  'currency': 'Ruble',
  'population': 145870000}]

## Retrieving data from a ```dictionary```

```dictionary_name.get("key")```

In [71]:
## run this single dictionary
usa = {'GDP': '$20.4 trillion',
 'NATO': True,
 'capital': 'Washington, DC',
 'country': 'United States',
 'currency': 'Dollar',
 'population': 329450000}

In [72]:
## is the USA a member of nato?
usa.get('NATO')

True

In [73]:
## what is the US currency?
usa.get('currency')

'Dollar'

## Retrieving data from a list of dictionaries

In [74]:
## call our countries dictionary just to see it again
country_stats

[{'GDP': '$20.4 trillion',
  'NATO': True,
  'capital': 'Washington, DC',
  'country': 'United States',
  'currency': 'Dollar',
  'population': 329450000},
 {'GDP': '$1.4 trillion',
  'NATO': False,
  'capital': 'Moscow',
  'country': 'Russia',
  'currency': 'Ruble',
  'population': 145870000},
 {'GDP': '$155 Billion',
  'NATO': False,
  'capital': 'Kiev',
  'country': 'Ukraine',
  'currency': 'Hrywnja',
  'population': 44135000}]

In [75]:
## Is the 2nd dictionary item a member of NATO?
country_stats[1].get('NATO')

False

In [76]:
## what is capital of the 3rd dictionary item?
country_stats[2].get('capital')

'Kiev'